name: Check for docs updates

on:
  workflow_dispatch: {}
  repository_dispatch:
    types: [docs-update]
  schedule:
    # run this during the week, tuesday to friday
    # at 9:10am, 9:10pm
    # Redmond time (UTC-7)
    - cron: '10 16,4 * * 2-5'

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  check:
    if: github.repository == 'bedrock-dot-dev/docs' && (github.ref == 'refs/heads/master' || github.event_name == 'workflow_dispatch')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v6

      - parallel:
          - name: Checkout stable documentation 🛎️
            uses: actions/checkout@v6
            with:
              repository: Mojang/bedrock-samples
              ref: main
              path: scripts/cache/stable
              fetch-depth: 1
              persist-credentials: false
              sparse-checkout: |
                /documentation/
                /version.json
              sparse-checkout-cone-mode: false

          - name: Checkout preview documentation 🛎️
            uses: actions/checkout@v6
            with:
              repository: Mojang/bedrock-samples
              ref: preview
              path: scripts/cache/preview
              fetch-depth: 1
              persist-credentials: false
              sparse-checkout: |
                /documentation/
                /version.json
              sparse-checkout-cone-mode: false

          - name: Setup Python 🐍
            uses: actions/setup-python@v6
            with:
              python-version: '3.14'

      - name: Setup git environment ⚙️
        if: github.ref == 'refs/heads/master'
        run: |
          git config user.name 'destruc7i0n'
          git config user.email 'destruc7i0n@users.noreply.github.com'

      - name: Check for docs update 🔎
        id: check
        env:
          DRY_RUN: ${{ github.ref != 'refs/heads/master' }}
        working-directory: scripts
        run: |
          python3 update.py

      - name: Update summary 📝
        run: |
          echo "### Check output 🗒️" >> $GITHUB_STEP_SUMMARY
          echo "Dry run: ${{ github.ref != 'refs/heads/master' }}" >> $GITHUB_STEP_SUMMARY
          echo "Update found: ${{ (steps.check.outputs.update == 'true' && '✅') || '❌' }}" >> $GITHUB_STEP_SUMMARY
          echo 'JSON output: `${{ steps.check.outputs.version_data }}`' >> $GITHUB_STEP_SUMMARY
          if [ "${{ steps.check.outputs.update }}" == "true" ]; then
            echo 'Commit message: ${{ steps.check.outputs.msg }}' >> $GITHUB_STEP_SUMMARY
          fi

      - name: Send Discord message 🔔
        if: steps.check.outputs.update == 'true' && github.ref == 'refs/heads/master'
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          LAST_COMMIT_SHA=$(git rev-parse HEAD)
          jq -nr '{
            "content": null,
            "embeds": [
              {
                "title": "Docs update: **${{ steps.check.outputs.msg }}**",
                "url": "https://github.com/${{ github.repository }}/commit/'"$LAST_COMMIT_SHA"'",
              }
            ],
            "username": "bedrock.dev",
            "avatar_url": "https://bedrock.dev/favicon/android-chrome-512x512.png",
          }' | curl --fail-with-body --silent --show-error -X POST -H "Content-Type: application/json" -d @- "$DISCORD_WEBHOOK"

      - name: Archive documentation files 📁
        if: steps.check.outputs.update == 'true'
        uses: actions/upload-artifact@v6
        with:
          name: ${{ steps.check.outputs.msg }}
          path: scripts/tmp
      
      - name: Deploy site 🚀
        if: steps.check.outputs.update == 'true' && github.ref == 'refs/heads/master'
        env:
          VERCEL_DEPLOY_HOOK: ${{ secrets.VERCEL_DEPLOY_HOOK }}
        run: |
          # sleep for a bit for GitHub's cache
          sleep 10s
          curl --fail-with-body --silent --show-error -X POST "$VERCEL_DEPLOY_HOOK"
